apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-mysql-deployment
spec:
  selector:
    matchLabels:
      app: springboot-mysql-deployment
  replicas: 3
  template:
    metadata:
      labels:
        app: springboot-mysql-deploymentl
    spec:
      containers:
        - name: springboot-mysql-deployment
          image: springboot-k8s:latest #i get it from docker hub
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
          env:   # Setting Enviornmental Variables
            - name: DB_HOST   # Setting Database host address from configMap
              value: mysql-k8s
            - name: DB_NAME  # Setting Database name from configMap
              value: test
            - name: DB_USERNAME  # Setting Database username from Secret
              value: root
            - name: DB_PASSWORD # Setting Database password from Secret
              value: root
---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: springboot-mysql-deployment
spec:
  selector:
    app: springboot-mysql-deploymentl
  ports:
    - protocol: TCP
      port: 8082 # The port that the service is running on in the cluster
      targetPort: 8082 # The port exposed by the service
  type: NodePort # type of the service.

